name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Change the Node.js version if needed

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Adjust the build command if different

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist # Replace 'dist' with your build output directory
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: GitHub Actions
          user_email: actions@users.noreply.github.com
          publish_branch: gh-pages # Change the branch name if needed
